/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IBLibrary;

import com.dropbox.core.DbxDownloader;
import com.dropbox.core.DbxException;
import com.dropbox.core.DbxRequestConfig;
import com.dropbox.core.v2.DbxClientV2;
import com.dropbox.core.v2.files.DownloadZipResult;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author belkina_ea
 */
public class MenuStudent extends javax.swing.JFrame {
    //initialize global variables
    String Subject;
    String type;
          

    /**
     * Creates new form MenuStudent
     */
    public MenuStudent() {
        initComponents();
        SubjectIA.hide(); //initially hide lists of the subjects
        SubjectEA.hide();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelStudent = new javax.swing.JPanel();
        TypeOfWork = new javax.swing.JComboBox<>();
        SubjectEA = new javax.swing.JComboBox<>();
        SubjectIA = new javax.swing.JComboBox<>();
        Download = new javax.swing.JButton();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TypeOfWork.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose the work type", "Internal Assessment", "External Assessment" }));
        TypeOfWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeOfWorkActionPerformed(evt);
            }
        });

        SubjectEA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose subject", "Biology", "Business&Management", "Chemistry", "Computer Science", "Economics", "ESS", "French", "Geography", "History", "Mathematics", "Russian A: Literature", "HL Essay in Russian A", "Visual Arts" }));

        SubjectIA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose subject", "Biology", "Business&Management", "Chemistry", "Computer Science", "Economics", "ESS", "French", "Geography", "History", "Mathematics", "Russian A: Literature", "Visual Arts", " " }));

        Download.setText("Download archive");
        Download.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownloadActionPerformed(evt);
            }
        });

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelStudentLayout = new javax.swing.GroupLayout(PanelStudent);
        PanelStudent.setLayout(PanelStudentLayout);
        PanelStudentLayout.setHorizontalGroup(
            PanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelStudentLayout.createSequentialGroup()
                .addGroup(PanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelStudentLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(PanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubjectIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubjectEA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TypeOfWork, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelStudentLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(Download))
                    .addGroup(PanelStudentLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(Logout)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        PanelStudentLayout.setVerticalGroup(
            PanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelStudentLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(TypeOfWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(SubjectEA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SubjectIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Download)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(Logout)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void TypeOfWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeOfWorkActionPerformed

        
        type = (String)TypeOfWork.getSelectedItem();
        if (type == "Internal Assessment") { //if the subject type is IA, then display the list of IA's subjects
            SubjectIA.setVisible(true);
            SubjectEA.hide();    
            Subject = (String)SubjectIA.getSelectedItem();
              
        }   
 
        else {
            if (type == "External Assessment") { //if the subject type is EA, then display the list of EA's subjects
                SubjectEA.setVisible(true);
                SubjectIA.hide();
                Subject = (String)SubjectEA.getSelectedItem();
                
            }
            else {
                SubjectIA.hide();
                SubjectEA.hide();
            }
        }
    }//GEN-LAST:event_TypeOfWorkActionPerformed
    
    
    private void DownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownloadActionPerformed
        String ACCESS_TOKEN = "qjJO82cebXkAAAAAAAAAAaSHnRTGVAb3UF7mAcIuc79khce3w2-AY4K15-eIYb5y"; //unique token to connect to dropbox
        type = (String)TypeOfWork.getSelectedItem();
        Subject = (String)SubjectEA.getSelectedItem();
        
        DbxRequestConfig config = DbxRequestConfig.newBuilder("dropbox/java-tutorial").build();
        DbxClientV2 client = new DbxClientV2(config, ACCESS_TOKEN); //make a client to access the online storage
        
        String folderPath = "/"+type+"/"+Subject+"/"; //create a folder path
        
        try {
            DbxDownloader<DownloadZipResult> downloader = client.files().downloadZip(folderPath); //choose the intended folder
            FileOutputStream out = new FileOutputStream(Subject+".zip"); //create the downloading stream
            downloader.download(out); //download
            out.close();
            } catch (DbxException ex) {
                System.out.println(ex.getMessage());
            } catch (IOException ex) {
                Logger.getLogger(MenuStudent.class.getName()).log(Level.SEVERE, null, ex);
            }
           
    }//GEN-LAST:event_DownloadActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        Login m = new Login();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Download;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel PanelStudent;
    private javax.swing.JComboBox<String> SubjectEA;
    private javax.swing.JComboBox<String> SubjectIA;
    private javax.swing.JComboBox<String> TypeOfWork;
    // End of variables declaration//GEN-END:variables
}

